export const en = {
  // Navigation & Header
  nav: {
    brand: "FarmSheild",
    tagline: "Digital Farm & Health Portal",
    farmerRole: "Farmer Mode",
    vetRole: "Veterinarian",
    adminRole: "Admin",
    qrScan: "Scan QR",
    language: "Language",
    english: "English",
    hindi: "हिंदी (Hindi)",
  },

  // Farmer Home Dashboard
  farmerHome: {
    greeting: "Namaste 👋",
    subGreeting: "Your Farm Safety & Livestock Portal",
    stats: {
      totalAnimals: "Total Animals",
      underTreatment: "Under Treatment",
      underWithdrawal: "Under Withdrawal",
      cleared: "Milk Safe to Sell",
    },
    actions: {
      myAnimals: "My Animals",
      myAnimalsDesc: "View & register livestock",
      recordMedicine: "Record Medicine",
      recordMedicineDesc: "Log medicine given to animal",
      isMilkSafe: "Is My Milk Safe?",
      isMilkSafeDesc: "Check sell status & safe dates",
      warnings: "Warnings & Alerts",
      warningsDesc: "Withdrawal & safety alerts",
      myRecords: "Treatment History",
      myRecordsDesc: "Past medicine records",
      scanQr: "Scan Animal QR",
      scanQrDesc: "Check animal status via QR",
    },
  },

  // Animal Management
  animals: {
    title: "My Animals",
    registerNew: "Register New Animal",
    animalCode: "Tag / ID Code",
    species: "Species",
    breed: "Breed",
    age: "Age / DOB",
    weight: "Weight (kg)",
    purpose: "Purpose",
    healthStatus: "Health Status",
    qrCode: "QR Token",
    viewProfile: "View Profile",
    generateQr: "Generate QR Code",
    noAnimals: "No animals registered yet. Click above to add your first animal.",
    status: {
      healthy: "Healthy 🟢",
      sick: "Sick 🟡",
      underTreatment: "Under Treatment 💊",
      quarantine: "Quarantine 🔴",
    },
    speciesList: {
      cow: "Cow (गाय)",
      buffalo: "Buffalo (भैंस)",
      goat: "Goat (बकरी)",
      sheep: "Sheep (भेड़)",
    },
    purposes: {
      milk: "Milk Production",
      meat: "Meat Production",
      breeding: "Breeding",
      other: "Other",
    },
  },

  // Medicine & Treatment Recording
  treatment: {
    title: "Record Medicine Treatment",
    subtitle: "Log medicine given to an animal to calculate safe milk/meat dates",
    selectAnimal: "Select Animal",
    selectMedicine: "Select Medicine",
    dose: "Dose Amount",
    doseUnit: "Dose Unit",
    route: "Route (How Given)",
    frequency: "Frequency",
    durationDays: "Duration (Days)",
    startDate: "Treatment Start Date",
    diseaseIndication: "Disease / Reason",
    productAffected: "Affected Product",
    veterinarianName: "Attending Veterinarian",
    notes: "Notes",
    submit: "Save Treatment & Calculate Safe Date",
    calculating: "Calculating Withdrawal Period...",
    successMsg: "Treatment logged successfully! Safe date calculated.",
    preview: {
      calculatedSafeDate: "Expected Safe Sell Date:",
      withdrawalDays: "Required Withdrawal Wait:",
      daysText: "days after treatment ends",
    },
  },

  // Milk & Product Safety Check
  withdrawal: {
    title: "Is My Milk Safe to Sell?",
    subtitle: "Real-time safety check for milk, meat, and eggs from treated livestock",
    safeTitle: "🥛 MILK IS SAFE TO SELL",
    safeSub: "No active medicine withdrawal period.",
    unsafeTitle: "🔴 DON'T SELL THIS MILK TODAY",
    unsafeSub: "Medicine is still active in animal's body.",
    reviewTitle: "🟡 REVIEW REQUIRED",
    reviewSub: "Regulatory rule missing or manual vet check required.",
    safeAfter: "Safe to sell after:",
    remainingDays: "Days remaining:",
    medicineUsed: "Medicine Given:",
    treatmentEnded: "Treatment Ended:",
    allAnimalsSafe: "All animals currently have safe milk!",
  },

  // Alerts & Notifications
  alerts: {
    title: "Warnings & Alerts",
    subtitle: "Important compliance and product safety warnings",
    critical: "Critical Alert 🔴",
    warning: "Warning 🟡",
    info: "Information 🟢",
    noAlerts: "No active warnings. All farm records are compliant!",
    resolveAlert: "Mark Resolved",
  },

  // QR Code Scanner & Public Profile
  qr: {
    scannerTitle: "Animal Safety QR Lookup",
    scanSubtitle: "Scan or enter animal QR token to view instant safety profile",
    enterTokenPlaceholder: "Enter QR Token (e.g. QR-COW-102)",
    lookupBtn: "Check Status",
    publicProfileTitle: "Animal Safety Certificate",
    publicNotice: "Official Public Withdrawal & Safety Status",
    tagCode: "Animal ID Code:",
    speciesBreed: "Species & Breed:",
    safetyStatus: "Current Safety Status:",
    clearedStatus: "🟢 CLEARED FOR SALE",
    withdrawalActive: "🔴 WITHDRAWAL PERIOD ACTIVE",
    reviewRequired: "🟡 REVIEW REQUIRED",
    disclaimer: "This digital badge is generated by FarmSheild MRL & Withdrawal Decision Support Engine.",
  },

  // Veterinarian Dashboard
  vet: {
    title: "Veterinarian Clinical Dashboard",
    subtitle: "Antimicrobial Usage (AMU) analytics, compliance risks & treatment reviews",
    assignedFarms: "Assigned Farms",
    activeTreatments: "Active Treatments",
    complianceRisks: "Compliance Risks",
    amuTrend: "Monthly AMU Trend",
    topMedicines: "Most Used Antimicrobials",
    repeatedAlerts: "Repeated Treatment Alerts",
    approveTreatment: "Approve Treatment",
  },

  // Admin Dashboard
  admin: {
    title: "System Administration Portal",
    subtitle: "Manage medicines catalog, FSSAI regulatory MRL rules, and audit logs",
    manageMedicines: "Medicines Catalog",
    manageRules: "Regulatory MRL Rules",
    addMedicine: "Add Medicine",
    addRule: "Add MRL Rule",
    jurisdiction: "Jurisdiction (e.g., FSSAI India)",
    mrlLimit: "MRL Limit (e.g. 4 ug/kg)",
    withdrawalPeriodDays: "Withdrawal Period (Days)",
  },

  // Common UI Buttons & Labels
  common: {
    cancel: "Cancel",
    save: "Save",
    loading: "Loading...",
    backToHome: "Back to Home",
    close: "Close",
    refresh: "Refresh",
    active: "Active",
    completed: "Completed",
    unknown: "Unknown",
  },
};

export type TranslationKeys = typeof en;
